function About() {
    return ( 
    <div>
        <h1>About</h1>
        <p>
        AND I RECENTLY COMPLETED A WEB DEVELOPMENT BOOTCAMP AT LE WAGON BRUSSELS. 
        I HAVE A PASSION FOR CODING AND PROBLEM SOLVING, AND LOVE BUILDING WEBSITES AND APPLICATIONS. 
        IN MY FREE TIME, I ENJOY WATCHING MOVIES, TV SHOWS, AND PLAYING FOOTBALL. 
        I'M EXCITED TO USE THE SKILLS I LEARNED AT LE WAGON TO CREATE IMPACTFUL AND USER-FRIENDLY WEBSITES FOR MY CLIENTS.
        </p>
    </div> );
}

export default About;